# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:11
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.FileField(upload_to=core.models.get_data_upload_to)),
                ('data_upload_uuid', models.CharField(max_length=32)),
                ('col_ts', models.CharField(max_length=255)),
                ('col_val', models.CharField(max_length=255)),
                ('ts_format', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-updated'],
            },
        ),
    ]
